server:
  port: 30170
  servlet:
    context-path: /h-dbc
    session:
      cookie:
        http-only: true
        max-age: ${spring.mvc.interceptors.login.cookie-max-age-sec}
        secure: false
        same-site: strict
        path: /
        name: h-dbc-sid
      timeout: 30m

mybatis:
  mapper-locations:
    - classpath*:mappers/*.xml
    - classpath*:**/mapper/common/*Mapper.xml
    - classpath*:**/mapper/embedded/*Mapper.xml
  config-location: classpath:jpaConfig-embedded.xml
mybatis-plus:
  mapper-locations: ${mybatis.mapper-locations}
  config-location: ${mybatis.config-location}

spring:
  application:
    name: h-dbc
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/message
    encoding: UTF-8
  mvc:
    interceptors:
      mdc:
        enabled: true
      api-safe:
        enabled: false
        include-path-patterns:
          - /hbq969-common/**
          - /hbq969-dict/**
          - /hbq969-tabula/**
        header-name: api-safe-token
        header-value-regex: ENC(3nSTj512SWemElbk1rzkLVrcoUntPtEQCv5HCi7ZevwSYx5ik+af4tRrGQdXc/c39LrqIWff8CQSv+APj3YQ9umBRQRSLxb6autlhZYa5d4=)
      resource-handler-registry:
        entries:
          - handlers: /hbq969-common/**
            locations: classpath:/static/hbq969-common/
          - handlers: /hbq969-dict/**
            locations: classpath:/static/hbq969-dict/
          - handlers: /hbq969-tabula/**
            locations: classpath:/static/hbq969-tabula/
          - handlers: /hbq969-sm/**
            locations: classpath:/static/hbq969-sm/
          - handlers: /dbc-ui/**
            locations: classpath:/static/dbc-ui/
        enabled: true
      login:
        enabled: true
        cookie-max-age-sec: 1800
        dialect: embedded
        include-urls:
          - "/hbq969-common/**"
          - "/hbq969-sm/**"
          - "/hbq969-dict/**"
          - "/hbq969-tabula/**"
          - "/common/encrypt/**"
          - "/ui-gw/**"
          - "/**/doc.html"
          - "/**/swagger-ui.html"
          - "/**/api-docs"
          - "/dbc-ui/**"
        exclude-urls:
          - "/**/error"
          - "/common/health"
          - "/hbq969-sm/index.html"
          - "/hbq969-sm/**/*.js"
          - "/hbq969-sm/**/*.css"
          - "/hbq969-sm/**/*.png"
          - "/hbq969-sm/**/*.jpg"
          - "/hbq969-sm/**/*.map"
          - "/hbq969-sm/**/*.ico"
          - "/hbq969-sm/**/login"
        session-key: h-dbc-sid

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969
      default-lookup-key: hikari
    hikari:
      jdbc-url: jdbc:h2:file:${user.dir}/.h2/dbc;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
      driver-class-name: org.h2.Driver
      username: h-dbc
      password: ENC(PQWxMysuG2mMhw2IpXF9BudyHe2cS5hL3nPx6tJBvYJLl9dZ2eSkBhU6ed7FDgQZ)
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: ${spring.application.name}
    password: ENC(PQWxMysuG2mMhw2IpXF9BudyHe2cS5hL3nPx6tJBvYJLl9dZ2eSkBhU6ed7FDgQZ)

swagger:
  base-package: com
  api-info:
    title: web应用Restful API
    description: web应用Restful API
    termsOfServiceUrl: http://127.0.0.1:${server.port}
    version: v1.0
    license: Apache LICENSE-2.0
    licenseUrl: https://apache.org/licenses/LICENSE-2.0.txt

dict:
  enabled: true
  reload:
    cron: 0 */30 * * * *
  map-key-prefix: fmt

encrypt:
  config:
    enabled: true
  restful:
    enabled: true
    aes:
      key: ENC(OpRRNfzeB0cKPdoQ3BLEc+WoW83lR9LHmRRN9xd/6nokMnYav1QBYNBLvxMyAsbUMlNVpfbVAD4f/E6WtTLaFw==)
      show-log: true
    advice-packages:
      - com.github.hbq969.middleware
      - com.github.hbq969.code.sm

advice:
  log:
    enabled: true
  restful-limit:
    enabled: true

dbc:
  backup: true
  auth:
    basic:
      key: Authorization
      include-urls:
        - "/api/**"
    enabled: true